
install.packages("tidyverse", dependencies = TRUE, ask = FALSE)
install.packages("readxl")
install.packages("readr")
install.packages("pacman")
install.packages("leaflet")
install.packages("openxlsx")
install.packages("ggplot2")
install.packages("writexl")
install.packages("stargazer")
install.packages("zoo")
install.packages("rvest")
install.packages("Matrix")
install.packages("openxlsx")
install.packages("cowplot")
install.packages("rio")
install.packages("plotly")
install.packages("reshape2")
install.packages("lubridate")
install.packages("plm")
install.packages("dplyr")
library(leaflet)
library(ggplot2)
library(openxlsx)
library(pacman)
library(readxl)
library(dplyr)
library(writexl)
library(stargazer)
library(tidyverse)
library(rvest)
library(readr)
library(broom)
library(Matrix)
library(openxlsx)
library(cowplot)
library(rio)
library(plotly)
library(reshape2)
library(lubridate)
library(zoo)
library(plm)


https://github.com/cherm7/Import_CAFTA/blob/main/Import_Cafta_2005-2012.xlsx
https://github.com/cherm7/Import_CAFTA/blob/main/Import_Cafta_2013-2024.xlsx
